sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
linkReplacements:
  - LICENSE-exasol-jdbc.txt|https://www.exasol.com/support/secure/attachment/155343/EXASOL_SDK-7.0.11.tar.gz
excludes:
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release_droid_release_on_maven_central.yml'"
